version: '3.9'

services:
  db:
    container_name: sport-dev-db
    image: postgres:15.2-alpine
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env.dev
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  postgres: