version: '3.9'

services:
  blog:
    container_name: sport-be
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 3001
    env_file: .env
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    container_name: sport-db
    image: postgres:15.2-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - sport_postgres:/var/lib/postgresql/data
      - ./migrations:/app/migrations
      - ./scripts:/app/scripts

volumes:
  sport_postgres: