CREATE TABLE IF NOT EXISTS exercises_trainings (
    id SERIAL PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
    training_id integer NOT NULL REFERENCES trainings(id) ON DELETE CASCADE REFERENCES trainings(id) DEFERRABLE INITIALLY DEFERRED,
    exercise_id integer NOT NULL REFERENCES exercises(id) ON DELETE CASCADE REFERENCES exercises(id) DEFERRABLE INITIALLY DEFERRED
);

