CREATE TABLE IF NOT EXISTS dates (
    id SERIAL PRIMARY KEY,
    value VARCHAR(250) NOT NULL,
    comment VARCHAR(500),
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
    training_id integer NOT NULL REFERENCES trainings(id) ON DELETE CASCADE REFERENCES trainings(id) DEFERRABLE INITIALLY DEFERRED
);

