CREATE TABLE IF NOT EXISTS iterations (
    id SERIAL PRIMARY KEY,
    time INT DEFAULT 0 NOT NULL,
    weight INT DEFAULT 0 NOT NULL,
    repeat INT DEFAULT 0 NOT NULL,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
    date_id integer NOT NULL REFERENCES dates(id) ON DELETE CASCADE REFERENCES dates(id) DEFERRABLE INITIALLY DEFERRED,
    exercise_id integer NOT NULL REFERENCES exercises(id) ON DELETE CASCADE REFERENCES exercises(id) DEFERRABLE INITIALLY DEFERRED
);